version: 2
updates:

  # Maintain dependencies for the root package
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:15"
      timezone: "Europe/Madrid"
