name: Release alpha
inputs:
  github-token:
    description: Token to push code with
    required: true
  npm-token:
    description: Token to push code with
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure git user
      shell: bash
      run: |
        git config --local user.email "x@empathy.co"
        git config --local user.name "empathy/x"
    - name: Create .npmrc file with authorization token
      run: echo //registry.npmjs.org/:_authToken=${inputs.npm-token} > .npmrc
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.github-token }}
    - name: Publish release
      run: npm run release:alpha
      shell: bash
    - name: Push changes to GitHub
      run: git push --follow-tags
      shell: bash
