name: Prepare release
on:
  workflow_dispatch:
    inputs:
      kind:
        default: stable
        required: false
        description: 'The type of the release: `stable` if you want a stable version, or `alpha` if you want a pre-release. Defaults to `stable`.'
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install lerna and all packages
        run: npm install
      - name: Build all packages
        run: npm run build
      #- name: Run linter in all packages
      #  run: npm run lint
      #- name: Run tests in all packages
      #  run: npm run test
      - name: Check status
        run: git status
      - name: Configure git user
        run: |
          git config --local user.email "x@empathy.co"
          git config --local user.name "empathy/x"
      - name: Prepare the release
        run: 'npm run prepare-release:${{ github.event.inputs.kind }}'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          commit-message: 'chore(release): prepare ${{ github.event.inputs.kind }} release'
          title: '${{ github.event.inputs.kind }} release'
          body: 'Preparation of the release'
          branch: 'release'
