name: Release new version
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
  release:
    if: ${{ github.ref == 'refs/heads/release' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install lerna and all packages
        run: npm install
      - name: Build all packages
        run: npm run build
      #- name: Run linter in all packages
      #  run: npm run lint
      #- name: Run tests in all packages
      #  run: npm run test
      #- name: Publish the changed packages
      #  run: npm run publish

